## Site metadata ##

title: Jekyll Actions Guide
description: How to setup GH Pages + GH Actions for use with Jekyll 4

### Built settings ###

url: "https://gixlabs.github.io"
baseurl: "/"

github_username: GIXLabs

theme: minima
